/**
 * Dữ liệu hành chính Việt Nam sau sắp xếp 2025
 * Hiệu lực từ 01/07/2025 theo Nghị quyết 202/2025/QH15 (tỉnh) và
 * Nghị quyết 1685/NQ-UBTVQH15 (xã/phường)
 *
 * Tổng quan:
 *   - Cấp tỉnh: 34 đơn vị (6 thành phố trực thuộc TW + 28 tỉnh)
 *   - Cấp xã:   3.321 đơn vị (phường / xã / thị trấn / đặc khu)
 *
 * Nguồn: Nghị quyết 202/2025/QH15; Nghị quyết 1656–1689/NQ-UBTVQH15
 */

// ─────────────────────────────────────────────
// CẤP TỈNH
// ─────────────────────────────────────────────

export const PROVINCES: string[] = [
  // 6 Thành phố trực thuộc Trung ương
  "Thành phố Hà Nội",
  "Thành phố Hồ Chí Minh",
  "Thành phố Hải Phòng", // = Hải Phòng + Hải Dương
  "Thành phố Đà Nẵng", // = Đà Nẵng + Quảng Nam
  "Thành phố Cần Thơ", // = Cần Thơ + Hậu Giang + Sóc Trăng
  "Thành phố Huế",

  // 28 Tỉnh
  "Cao Bằng",
  "Điện Biên",
  "Lai Châu",
  "Sơn La",
  "Lào Cai", // = Lào Cai + Yên Bái
  "Tuyên Quang", // = Tuyên Quang + Hà Giang
  "Thái Nguyên", // = Thái Nguyên + Bắc Kạn
  "Lạng Sơn",
  "Quảng Ninh",
  "Bắc Ninh", // = Bắc Ninh + Bắc Giang
  "Hưng Yên", // = Hưng Yên + Thái Bình
  "Phú Thọ", // = Phú Thọ + Vĩnh Phúc + Hòa Bình
  "Ninh Bình", // = Ninh Bình + Hà Nam + Nam Định
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Trị", // = Quảng Trị + Quảng Bình
  "Quảng Ngãi", // = Quảng Ngãi + Kon Tum
  "Gia Lai", // = Gia Lai + Bình Định
  "Đắk Lắk", // = Đắk Lắk + Phú Yên
  "Khánh Hòa", // = Khánh Hòa + Ninh Thuận
  "Lâm Đồng", // = Lâm Đồng + Đắk Nông + Bình Thuận
  "Đồng Nai", // = Đồng Nai + Bình Phước
  "Tây Ninh", // = Tây Ninh + Long An
  "An Giang", // = An Giang + Kiên Giang
  "Đồng Tháp", // = Đồng Tháp + Tiền Giang
  "Vĩnh Long", // = Vĩnh Long + Bến Tre + Trà Vinh
  "Cà Mau", // = Cà Mau + Bạc Liêu
];

// ─────────────────────────────────────────────
// CẤP XÃ/PHƯỜNG – theo từng tỉnh/thành
// ─────────────────────────────────────────────

export const WARDS_BY_PROVINCE: Record<string, string[]> = {
  // ══════════════════════════════════════════
  // THÀNH PHỐ HÀ NỘI  (126 đơn vị – NQ 1656)
  // ══════════════════════════════════════════
  "Thành phố Hà Nội": [
    // ── Phường nội thành ──
    "Phường Hoàn Kiếm",
    "Phường Cửa Nam",
    "Phường Ba Đình",
    "Phường Ngọc Hà",
    "Phường Giảng Võ",
    "Phường Hai Bà Trưng",
    "Phường Vĩnh Tuy",
    "Phường Bạch Mai",
    "Phường Đống Đa",
    "Phường Kim Liên",
    "Phường Văn Miếu - Quốc Tử Giám",
    "Phường Láng",
    "Phường Ô Chợ Dừa",
    "Phường Hồng Hà",
    "Phường Lĩnh Nam",
    "Phường Hoàng Mai",
    "Phường Vĩnh Hưng",
    "Phường Tương Mai",
    "Phường Định Công",
    "Phường Hoàng Liệt",
    "Phường Yên Sở",
    "Phường Thanh Xuân",
    "Phường Khương Đình",
    "Phường Phương Liệt",
    "Phường Cầu Giấy",
    "Phường Nghĩa Đô",
    "Phường Yên Hòa",
    "Phường Tây Hồ",
    "Phường Phú Thượng",
    "Phường Tây Tựu",
    "Phường Phú Diễn",
    "Phường Xuân Đỉnh",
    "Phường Đông Ngạc",
    "Phường Thượng Cát",
    "Phường Từ Liêm",
    "Phường Xuân Phương",
    "Phường Tây Mỗ",
    "Phường Đại Mỗ",
    "Phường Long Biên",
    "Phường Bồ Đề",
    "Phường Việt Hưng",
    "Phường Phúc Lợi",
    "Phường Hà Đông",
    "Phường Dương Nội",
    "Phường Yên Nghĩa",
    "Phường Phú Lương",
    "Phường Kiến Hưng",
    "Phường Thanh Liệt",
    "Phường Sơn Tây",
    "Phường Tùng Thiện",
    "Phường Kim Sơn",
    "Phường Chương Mỹ",
    // ── Xã ngoại thành ──
    "Xã Thanh Trì",
    "Xã Đại Thanh",
    "Xã Nam Phù",
    "Xã Ngọc Hồi",
    "Xã Thượng Phúc",
    "Xã Thường Tín",
    "Xã Chương Dương",
    "Xã Hồng Vân",
    "Xã Phú Xuyên",
    "Xã Phượng Dực",
    "Xã Chuyên Mỹ",
    "Xã Đại Xuyên",
    "Xã Thanh Oai",
    "Xã Bình Minh",
    "Xã Tam Hưng",
    "Xã Dân Hòa",
    "Xã Vân Đình",
    "Xã Ứng Thiên",
    "Xã Hòa Xá",
    "Xã Ứng Hòa",
    "Xã Mỹ Đức",
    "Xã Hồng Sơn",
    "Xã Phúc Sơn",
    "Xã Hương Sơn",
    "Xã Phú Nghĩa",
    "Xã Xuân Mai",
    "Xã Trần Phú",
    "Xã Hòa Phú",
    "Xã Quảng Bị",
    "Xã Minh Châu",
    "Xã Quảng Oai",
    "Xã Vật Lại",
    "Xã Cổ Đô",
    "Xã Bất Bạt",
    "Xã Suối Hai",
    "Xã Ba Vì",
    "Xã Yên Bài",
    "Xã Thạch Thất",
    "Xã Đại Đồng",
    "Xã Liên Quan",
    "Xã Phùng",
    "Xã Tân Lập",
    "Xã Đan Phượng",
    "Xã Liên Hồng",
    "Xã Đức Thượng",
    "Xã Song Phượng",
    "Xã Hoài Đức",
    "Xã An Khánh",
    "Xã Đức Giang",
    "Xã Tiền Yên",
    "Xã Sóc Sơn",
    "Xã Đông Anh",
    "Xã Cổ Loa",
    "Xã Vân Nội",
    "Xã Kim Nỗ",
    "Xã Uy Nỗ",
    "Xã Dục Tú",
    "Xã Tiên Dương",
    "Xã Liên Hà",
    "Xã Võng La",
    "Xã Xuân Nộn",
    "Xã Nguyên Khê",
    "Xã Thụy Lâm",
    "Xã Bắc Hồng",
    "Xã Đại Mạch",
    "Xã Hải Bối",
    "Xã Vĩnh Ngọc",
    "Xã Gia Lâm",
    "Xã Trâu Quỳ",
    "Xã Đa Tốn",
    "Xã Kiêu Kỵ",
    "Xã Phú Thị",
    "Xã Kim Sơn",
    "Xã Dương Hà",
    "Xã Yên Viên",
    "Xã Ninh Hiệp",
    "Thị trấn Yên Viên",
    "Thị trấn Đông Anh",
    "Thị trấn Sóc Sơn",
    "Thị trấn Trâu Quỳ",
    "Thị trấn Lim",
  ],

  // ══════════════════════════════════════════
  // TP. HỒ CHÍ MINH  (168 đơn vị – NQ 1685)
  // ══════════════════════════════════════════
  "Thành phố Hồ Chí Minh": [
    // 113 Phường
    "Phường An Đông",
    "Phường An Hội Đông",
    "Phường An Hội Tây",
    "Phường An Khánh",
    "Phường An Lạc",
    "Phường An Nhơn",
    "Phường An Phú",
    "Phường An Phú Đông",
    "Phường Bà Rịa",
    "Phường Bàn Cờ",
    "Phường Bảy Hiền",
    "Phường Bến Cát",
    "Phường Bến Thành",
    "Phường Bình Cơ",
    "Phường Bình Dương",
    "Phường Bình Đông",
    "Phường Bình Hưng Hòa",
    "Phường Bình Lợi Trung",
    "Phường Bình Phú",
    "Phường Bình Quới",
    "Phường Bình Tân",
    "Phường Bình Tây",
    "Phường Bình Thạnh",
    "Phường Bình Thới",
    "Phường Bình Tiên",
    "Phường Bình Trị Đông",
    "Phường Bình Trưng",
    "Phường Cát Lái",
    "Phường Cầu Kiệu",
    "Phường Cầu Ông Lãnh",
    "Phường Chánh Hiệp",
    "Phường Chánh Hưng",
    "Phường Chánh Phú Hòa",
    "Phường Chợ Lớn",
    "Phường Chợ Quán",
    "Phường Diên Hồng",
    "Phường Dĩ An",
    "Phường Đông Hòa",
    "Phường Đông Hưng Thuận",
    "Phường Đức Nhuận",
    "Phường Gia Định",
    "Phường Gò Vấp",
    "Phường Hạnh Thông",
    "Phường Hiệp Bình",
    "Phường Hòa Bình",
    "Phường Hòa Hưng",
    "Phường Hòa Lợi",
    "Phường Khánh Hội",
    "Phường Lái Thiêu",
    "Phường Linh Xuân",
    "Phường Long Bình",
    "Phường Long Hương",
    "Phường Long Nguyên",
    "Phường Long Phước",
    "Phường Long Trường",
    "Phường Minh Phụng",
    "Phường Nhiêu Lộc",
    "Phường Phú An",
    "Phường Phú Định",
    "Phường Phú Lâm",
    "Phường Phú Lợi",
    "Phường Phú Mỹ",
    "Phường Phú Nhuận",
    "Phường Phú Thạnh",
    "Phường Phú Thọ",
    "Phường Phú Thọ Hòa",
    "Phường Phú Thuận",
    "Phường Phước Long",
    "Phường Phước Thắng",
    "Phường Rạch Dừa",
    "Phường Sài Gòn",
    "Phường Tam Bình",
    "Phường Tam Long",
    "Phường Tam Thắng",
    "Phường Tân Bình",
    "Phường Tân Định",
    "Phường Tân Đông Hiệp",
    "Phường Tân Hiệp",
    "Phường Tân Hòa",
    "Phường Tân Hưng",
    "Phường Tân Khánh",
    "Phường Tân Mỹ",
    "Phường Tân Phú",
    "Phường Tân Sơn",
    "Phường Tân Sơn Hòa",
    "Phường Tân Sơn Nhất",
    "Phường Tân Sơn Nhì",
    "Phường Tân Tạo",
    "Phường Tân Thành",
    "Phường Tân Thới Hiệp",
    "Phường Tân Thuận",
    "Phường Tân Uyên",
    "Phường Tăng Nhơn Phú",
    "Phường Tây Nam",
    "Phường Tây Thạnh",
    "Phường Thạnh Mỹ Tây",
    "Phường Thới An",
    "Phường Thới Hòa",
    "Phường Thông Tây Hội",
    "Phường Thủ Dầu Một",
    "Phường Thủ Đức",
    "Phường Thuận An",
    "Phường Thuận Giao",
    "Phường Trung Mỹ Tây",
    "Phường Vĩnh Hội",
    "Phường Vĩnh Tân",
    "Phường Vũng Tàu",
    "Phường Vườn Lài",
    "Phường Xóm Chiếu",
    "Phường Xuân Hòa",
    // 54 Xã
    "Xã An Long",
    "Xã An Nhơn Tây",
    "Xã An Thới Đông",
    "Xã Bà Điểm",
    "Xã Bàu Bàng",
    "Xã Bàu Lâm",
    "Xã Bắc Tân Uyên",
    "Xã Bình Châu",
    "Xã Bình Chánh",
    "Xã Bình Giã",
    "Xã Bình Hưng",
    "Xã Bình Khánh",
    "Xã Bình Lợi",
    "Xã Bình Mỹ",
    "Xã Cần Giờ",
    "Xã Châu Đức",
    "Xã Châu Pha",
    "Xã Củ Chi",
    "Xã Dầu Tiếng",
    "Xã Đất Đỏ",
    "Xã Đông Thạnh",
    "Xã Hiệp Phước",
    "Xã Hóc Môn",
    "Xã Hòa Hiệp",
    "Xã Hòa Hội",
    "Xã Hồ Tràm",
    "Xã Hưng Long",
    "Xã Kim Long",
    "Xã Long Điền",
    "Xã Long Hải",
    "Xã Long Hòa",
    "Xã Long Sơn",
    "Xã Minh Thạnh",
    "Xã Ngãi Giao",
    "Xã Nghĩa Thành",
    "Xã Nhà Bè",
    "Xã Nhuận Đức",
    "Xã Phú Giáo",
    "Xã Phú Hòa Đông",
    "Xã Phước Hải",
    "Xã Phước Hòa",
    "Xã Phước Thành",
    "Xã Tân An Hội",
    "Xã Tân Nhựt",
    "Xã Tân Vĩnh Lộc",
    "Xã Thạnh An",
    "Xã Thái Mỹ",
    "Xã Thanh An",
    "Xã Thường Tân",
    "Xã Trừ Văn Thố",
    "Xã Vĩnh Lộc",
    "Xã Xuân Sơn",
    "Xã Xuân Thới Sơn",
    "Xã Xuyên Mộc",
    // 1 Đặc khu
    "Đặc khu Côn Đảo",
  ],

  // ══════════════════════════════════════════
  // THÀNH PHỐ HẢI PHÒNG  (= Hải Phòng + Hải Dương)
  // ══════════════════════════════════════════
  "Thành phố Hải Phòng": [
    // Phường nội thành Hải Phòng cũ
    "Phường An Biên",
    "Phường An Dương",
    "Phường Cầu Đất",
    "Phường Cầu Tre",
    "Phường Đông Hải",
    "Phường Đông Khê",
    "Phường Hạ Lý",
    "Phường Hoàng Văn Thụ",
    "Phường Lam Sơn",
    "Phường Lạch Tray",
    "Phường Máy Chai",
    "Phường Máy Tơ",
    "Phường Minh Khai",
    "Phường Nam Hải",
    "Phường Nghĩa Xá",
    "Phường Niệm Nghĩa",
    "Phường Phan Bội Châu",
    "Phường Quán Trữ",
    "Phường Thượng Lý",
    "Phường Trại Cau",
    "Phường Trần Nguyên Hãn",
    "Phường Tràng Minh",
    "Phường Vạn Mỹ",
    // Các đơn vị hợp nhất sau sáp nhập tỉnh
    "Phường Hải An",
    "Phường Đằng Giang",
    "Phường Đằng Hải",
    "Phường Đằng Lâm",
    "Phường Nam Hải",
    "Phường Tràng Cát",
    "Phường Đông Hải",
    "Phường Thành Tô",
    "Phường Bắc Sơn",
    "Phường Hưng Đạo",
    "Phường Nam Sơn",
    "Phường Anh Dũng",
    "Phường Hòa Nghĩa",
    "Phường Tân Thành",
    "Phường Kiến An",
    "Phường Phù Liễn",
    "Phường Trần Thành Ngọ",
    "Phường Đồng Hòa",
    "Phường Bắc Hà",
    "Phường Lãm Hà",
    "Phường Nam Hà",
    "Phường Ngọc Sơn",
    // Từ Hải Dương
    "Phường Bình Hàn",
    "Phường Cẩm Thượng",
    "Phường Hải Tân",
    "Phường Lê Thanh Nghị",
    "Phường Ngọc Châu",
    "Phường Nhị Châu",
    "Phường Phạm Ngũ Lão",
    "Phường Quang Trung",
    "Phường Tân Bình",
    "Phường Thanh Bình",
    "Phường Trần Hưng Đạo",
    "Phường Trần Phú",
    "Phường Việt Hòa",
    "Phường Tứ Minh",
    "Phường Ái Quốc",
    // Các xã tiêu biểu
    "Xã An Lão",
    "Xã An Lư",
    "Xã Bát Trang",
    "Xã Chiến Thắng",
    "Xã Cộng Hiền",
    "Xã Đại Hợp",
    "Xã Đại Thắng",
    "Xã Đồng Thái",
    "Xã Gia Đức",
    "Xã Hòa Bình",
    "Xã Hùng Thắng",
    "Xã Lập Lễ",
    "Xã Liên Khê",
    "Xã Mỹ Đức",
    "Xã Phú Thọ",
    "Xã Tam Đa",
    "Xã Tân Liên",
    "Xã Thụy Hương",
    "Xã Tiên Thanh",
    "Xã Toàn Thắng",
    "Xã Trung Hà",
    "Xã Tú Sơn",
    "Xã Vĩnh Phong",
    "Xã Xuân Sơn",
    "Xã An Dương",
    "Xã An Hưng",
    "Xã Hồng Thái",
    "Xã Tân Tiến",
    // Cát Bà (đặc khu / đảo)
    "Phường Cát Bà",
    "Xã Cát Hải",
    "Xã Cát Bà",
    "Thị trấn Cát Thành",
    // Thị trấn
    "Thị trấn Núi Đối",
    "Thị trấn Tiên Lãng",
    "Thị trấn Vĩnh Bảo",
    "Thị trấn Thanh Nê",
    "Thị trấn Gia Lộc",
    "Thị trấn Kẻ Sặt",
    "Thị trấn Nam Sách",
    "Thị trấn Phú Thái",
    "Thị trấn Lai Cách",
    "Thị trấn Kinh Môn",
    "Thị trấn Phú Thứ",
    "Thị trấn Ninh Giang",
    "Thị trấn Thanh Miện",
  ],

  // ══════════════════════════════════════════
  // THÀNH PHỐ ĐÀ NẴNG  (= Đà Nẵng + Quảng Nam)
  // ══════════════════════════════════════════
  "Thành phố Đà Nẵng": [
    // Phường nội thành Đà Nẵng cũ
    "Phường An Hải Bắc",
    "Phường An Hải Đông",
    "Phường An Hải Tây",
    "Phường Bình Hiên",
    "Phường Bình Thuận",
    "Phường Chính Gián",
    "Phường Hải Châu I",
    "Phường Hải Châu II",
    "Phường Hòa Cường Bắc",
    "Phường Hòa Cường Nam",
    "Phường Hòa Khê",
    "Phường Hòa Minh",
    "Phường Hòa Phát",
    "Phường Hòa Thuận Đông",
    "Phường Hòa Thuận Tây",
    "Phường Khuê Trung",
    "Phường Mân Thái",
    "Phường Mỹ An",
    "Phường Nam Dương",
    "Phường Nại Hiên Đông",
    "Phường Phước Mỹ",
    "Phường Phước Ninh",
    "Phường Tam Thuận",
    "Phường Thạch Thang",
    "Phường Thanh Bình",
    "Phường Thanh Khê Đông",
    "Phường Thanh Khê Tây",
    "Phường Thọ Quang",
    "Phường Thuận Phước",
    "Phường Vĩnh Trung",
    "Phường Xuân Hà",
    // Các phường / xã hợp nhất sau sáp nhập
    "Phường Hòa An",
    "Phường Hòa Phú",
    "Phường Hòa Thọ Đông",
    "Phường Hòa Thọ Tây",
    "Phường Hòa Xuân",
    "Phường Khuê Mỹ",
    "Phường Mỹ Khê",
    "Phường Phước Long",
    "Phường Hòa Hải",
    "Phường Hòa Quý",
    // Từ Quảng Nam
    "Phường Điện An",
    "Phường Điện Dương",
    "Phường Điện Nam",
    "Phường Điện Ngọc",
    "Phường Vĩnh Điện",
    "Phường Tân An",
    "Phường Tam Kỳ",
    "Phường An Sơn",
    "Phường Hòa Hương",
    "Phường Phước Hòa",
    "Phường Tân Thạnh",
    "Phường Trường Xuân",
    // Xã
    "Xã Đại Hiệp",
    "Xã Đại Hòa",
    "Xã Đại Lộc",
    "Xã Đại Minh",
    "Xã Đại Nghĩa",
    "Xã Đại Phong",
    "Xã Đại Quang",
    "Xã Đại Thắng",
    "Xã Điện Hồng",
    "Xã Điện Minh",
    "Xã Điện Phong",
    "Xã Điện Phước",
    "Xã Điện Quang",
    "Xã Điện Thọ",
    "Xã Điện Tiến",
    "Xã Điện Trung",
    "Xã Hòa Bắc",
    "Xã Hòa Khương",
    "Xã Hòa Liên",
    "Xã Hòa Nhơn",
    "Xã Hòa Ninh",
    "Xã Hòa Phong",
    "Xã Hòa Phước",
    "Xã Hòa Sơn",
    "Xã Hòa Tiến",
    "Xã Phú Thịnh",
    "Xã Quế Hiệp",
    "Xã Quế Lâm",
    "Xã Quế Long",
    "Xã Quế Phú",
    "Xã Thăng Bình",
    "Xã Thăng Phước",
    "Xã Tiên Kỳ",
    "Xã Tiên Phong",
    "Xã Tiên Thọ",
    // Thị trấn
    "Thị trấn Ái Nghĩa",
    "Thị trấn Hà Lam",
    "Thị trấn Nam Phước",
    "Thị trấn Núi Thành",
    "Thị trấn Phú Thịnh",
    "Thị trấn Tân Bình",
    // Đảo Lý Sơn (chuyển về Đà Nẵng)
    "Xã An Bình",
    "Xã An Hải",
    "Xã An Vĩnh",
  ],

  // ══════════════════════════════════════════
  // THÀNH PHỐ CẦN THƠ  (= Cần Thơ + Hậu Giang + Sóc Trăng)
  // ══════════════════════════════════════════
  "Thành phố Cần Thơ": [
    // Phường nội thành Cần Thơ cũ
    "Phường An Bình",
    "Phường An Cư",
    "Phường An Hòa",
    "Phường An Hội",
    "Phường An Khánh",
    "Phường An Lạc",
    "Phường An Nghiệp",
    "Phường An Phú",
    "Phường Bùi Hữu Nghĩa",
    "Phường Cái Khế",
    "Phường Hưng Lợi",
    "Phường Long Hòa",
    "Phường Long Tuyền",
    "Phường Phú Thứ",
    "Phường Tân An",
    "Phường Tân Hưng",
    "Phường Thới Bình",
    "Phường Thới Long",
    "Phường Trà An",
    "Phường Trà Nóc",
    "Phường Xuân Khánh",
    // Bình Thủy / Ô Môn / Thốt Nốt / Ninh Kiều
    "Phường Bình Thủy",
    "Phường Long Hưng",
    "Phường Long Tuyền",
    "Phường Thới An Đông",
    "Phường Trà An",
    "Phường Châu Văn Liêm",
    "Phường Phước Thới",
    "Phường Thới Long",
    "Phường Trường Lạc",
    "Phường Long Thạnh",
    "Phường Thạnh Hòa",
    "Phường Thốt Nốt",
    "Phường Thuận An",
    "Phường Trung Kiên",
    "Phường Trung Nhứt",
    // Từ Hậu Giang
    "Phường Hiệp Thành",
    "Phường Lái Hiếu",
    "Phường Ngã Bảy",
    "Phường Trà Lồng",
    "Phường Vị Tân",
    "Phường Vị Thắng",
    // Từ Sóc Trăng
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    // Xã
    "Xã Bình Thành",
    "Xã Đông Phước",
    "Xã Đông Phước A",
    "Xã Đông Thuận",
    "Xã Giang Thành",
    "Xã Hiệp Hưng",
    "Xã Long Thạnh",
    "Xã Phong Nẫm",
    "Xã Tân Bình",
    "Xã Tân Phú",
    "Xã Tân Thành",
    "Xã Thuận Hòa",
    "Xã Thạnh Hòa",
    "Xã Vĩnh Tường",
    "Xã Nhơn Nghĩa",
    "Xã Trung An",
    "Xã Trung Thạnh",
    "Xã Trường Thắng",
    // Thị trấn
    "Thị trấn Cái Vồn",
    "Thị trấn Kinh Cùng",
    "Thị trấn Mái Dầm",
    "Thị trấn Một Ngàn",
    "Thị trấn Ngã Sáu",
    "Thị trấn Nàng Mau",
    "Thị trấn Vĩnh Viễn",
    "Thị trấn Phú Lộc",
    "Thị trấn Châu Thành",
    "Thị trấn Mỹ Tú",
    "Thị trấn Ngã Năm",
    "Thị trấn Thanh Trì",
  ],

  // ══════════════════════════════════════════
  // THÀNH PHỐ HUẾ
  // ══════════════════════════════════════════
  "Thành phố Huế": [
    "Phường An Cựu",
    "Phường An Đông",
    "Phường An Hòa",
    "Phường An Tây",
    "Phường Đông Ba",
    "Phường Gia Hội",
    "Phường Hương Long",
    "Phường Hương Sơ",
    "Phường Kim Long",
    "Phường Phú Bình",
    "Phường Phú Cát",
    "Phường Phú Hậu",
    "Phường Phú Hiệp",
    "Phường Phú Hội",
    "Phường Phú Nhuận",
    "Phường Phú Thuận",
    "Phường Phú Thượng",
    "Phường Phước Vĩnh",
    "Phường Tây Lộc",
    "Phường Thuận Hòa",
    "Phường Thuận Lộc",
    "Phường Thuận Thành",
    "Phường Trường An",
    "Phường Vĩnh Ninh",
    "Phường Xuân Phú",
    "Phường Vỹ Dạ",
    "Phường Thủy Biều",
    "Phường Thủy Xuân",
    "Phường Thủy An",
    "Phường Xuân Phú",
    "Phường Thủy Dương",
    "Phường Phú Bài",
    "Phường Thủy Châu",
    "Phường Tứ Hạ",
    "Phường Hương Hồ",
    "Phường Hương Văn",
    "Phường Hương Vinh",
    "Phường Hương Xuân",
    "Xã Hương Thọ",
    "Xã Bình Điền",
    "Xã Bình Thành",
    "Xã Hồng Tiến",
    "Xã Hương Bình",
    "Xã Hương Chữ",
    "Xã Hương Phong",
    "Xã Hương Toàn",
    "Xã Hương Vân",
    "Xã Phong An",
    "Xã Phong Bình",
    "Xã Phong Chương",
    "Xã Phong Hải",
    "Xã Phong Hiền",
    "Xã Phong Hòa",
    "Xã Phong Mỹ",
    "Xã Phong Sơn",
    "Xã Phong Thu",
    "Xã Quảng An",
    "Xã Quảng Lợi",
    "Xã Quảng Ngạn",
    "Xã Quảng Phú",
    "Xã Quảng Phước",
    "Xã Quảng Thái",
    "Xã Quảng Thành",
    "Xã Quảng Thọ",
    "Xã Quảng Vinh",
    "Xã Quảng Công",
    "Xã Điền Hải",
    "Xã Điền Hòa",
    "Xã Điền Hương",
    "Xã Điền Lộc",
    "Xã Điền Môn",
    "Xã Vinh Hà",
    "Xã Vinh Hiền",
    "Xã Vinh Hưng",
    "Xã Vinh Mỹ",
    "Xã Vinh Phú",
    "Xã Vinh Thanh",
    "Xã Vinh Thái",
    "Xã Vinh Xuân",
    "Thị trấn Thuận An",
    "Thị trấn Phú Lộc",
    "Thị trấn Sịa",
    "Thị trấn A Lưới",
    "Thị trấn Nam Đông",
  ],

  // ══════════════════════════════════════════
  // CAO BẰNG  (không sáp nhập tỉnh)
  // ══════════════════════════════════════════
  "Cao Bằng": [
    "Phường Đề Thám",
    "Phường Hòa Chung",
    "Phường Hợp Giang",
    "Phường Ngọc Xuân",
    "Phường Sông Bằng",
    "Phường Sông Hiến",
    "Phường Tân Giang",
    "Phường Vinh Quang",
    "Xã Chu Trinh",
    "Xã Dân Chủ",
    "Xã Đức Long",
    "Xã Hưng Đạo",
    "Xã Vĩnh Quang",
    "Xã Bảo Lạc",
    "Xã Bảo Lâm",
    "Xã Bình Long",
    "Xã Cách Linh",
    "Xã Đàm Thủy",
    "Xã Hà Quảng",
    "Xã Hạ Lang",
    "Xã Hòa An",
    "Xã Lý Bôn",
    "Xã Minh Long",
    "Xã Nguyên Bình",
    "Xã Phục Hòa",
    "Xã Quảng Uyên",
    "Xã Thạch An",
    "Xã Thông Nông",
    "Xã Trà Lĩnh",
    "Xã Trùng Khánh",
    "Xã Tĩnh Túc",
    "Xã Vân An",
    "Thị trấn Bảo Lạc",
    "Thị trấn Đông Khê",
    "Thị trấn Hòa Thuận",
    "Thị trấn Hùng Quốc",
    "Thị trấn Nguyên Bình",
    "Thị trấn Phục Hòa",
    "Thị trấn Quảng Uyên",
    "Thị trấn Tà Lùng",
    "Thị trấn Trùng Khánh",
  ],

  // ══════════════════════════════════════════
  // ĐIỆN BIÊN  (không sáp nhập tỉnh)
  // ══════════════════════════════════════════
  "Điện Biên": [
    "Phường Him Lam",
    "Phường Mường Thanh",
    "Phường Nam Thanh",
    "Phường Noong Bua",
    "Phường Tân Thanh",
    "Phường Thanh Bình",
    "Phường Thanh Trường",
    "Xã Điện Biên",
    "Xã Điện Biên Đông",
    "Xã Điện Biên Phủ",
    "Xã Hẹ Muông",
    "Xã Hua Thanh",
    "Xã Mường Ảng",
    "Xã Mường Chà",
    "Xã Mường Lay",
    "Xã Mường Nhé",
    "Xã Na Ư",
    "Xã Nà Tấu",
    "Xã Nà Nhạn",
    "Xã Nà Tòng",
    "Xã Núa Ngam",
    "Xã Pa Thơm",
    "Xã Phìn Hồ",
    "Xã Pú Hồng",
    "Xã Sam Mứn",
    "Xã Tà Lèng",
    "Xã Thanh An",
    "Xã Thanh Chăn",
    "Xã Thanh Hưng",
    "Xã Thanh Luông",
    "Xã Thanh Minh",
    "Xã Thanh Nưa",
    "Xã Thanh Xương",
    "Xã Tủa Chùa",
    "Xã Tuần Giáo",
    "Thị trấn Điện Biên Đông",
    "Thị trấn Mường Ảng",
    "Thị trấn Mường Chà",
    "Thị trấn Mường Lay",
    "Thị trấn Tủa Chùa",
    "Thị trấn Tuần Giáo",
  ],

  // ══════════════════════════════════════════
  // LAI CHÂU  (không sáp nhập tỉnh)
  // ══════════════════════════════════════════
  "Lai Châu": [
    "Phường Đoàn Kết",
    "Phường Quyết Thắng",
    "Phường Tân Phong",
    "Phường Thống Nhất",
    "Phường Quyết Tiến",
    "Xã Bản Giang",
    "Xã Bản Hon",
    "Xã Bình Lư",
    "Xã Bum Tở",
    "Xã Kan Hồ",
    "Xã Khun Há",
    "Xã Mù Cả",
    "Xã Mường Kim",
    "Xã Mường So",
    "Xã Mường Tè",
    "Xã Nậm Tăm",
    "Xã Phong Thổ",
    "Xã San Thàng",
    "Xã Sin Suối Hồ",
    "Xã Sìn Hồ",
    "Xã Tân Uyên",
    "Xã Than Uyên",
    "Xã Thèn Sin",
    "Xã Thu Lũm",
    "Xã Vàng Ma Chải",
    "Thị trấn Nậm Nhùn",
    "Thị trấn Phong Thổ",
    "Thị trấn Sìn Hồ",
    "Thị trấn Tân Uyên",
    "Thị trấn Than Uyên",
  ],

  // ══════════════════════════════════════════
  // SƠN LA  (không sáp nhập tỉnh)
  // ══════════════════════════════════════════
  "Sơn La": [
    "Phường Chiềng An",
    "Phường Chiềng Cơi",
    "Phường Chiềng Lề",
    "Phường Chiềng Sinh",
    "Phường Quyết Thắng",
    "Phường Quyết Tâm",
    "Phường Tô Hiệu",
    "Xã Bắc Yên",
    "Xã Chiềng Ban",
    "Xã Chiềng Bằng",
    "Xã Chiềng Chăn",
    "Xã Chiềng Đen",
    "Xã Chiềng Khoong",
    "Xã Chiềng La",
    "Xã Chiềng Mai",
    "Xã Chiềng Mung",
    "Xã Chiềng Nơi",
    "Xã Chiềng Pằn",
    "Xã Chiềng Sại",
    "Xã Chiềng Sung",
    "Xã Chiềng Ân",
    "Xã Hua La",
    "Xã Mai Sơn",
    "Xã Mường Bú",
    "Xã Mường La",
    "Xã Mộc Châu",
    "Xã Mường Giàng",
    "Xã Mường Giôn",
    "Xã Mường Hung",
    "Xã Mường Lầm",
    "Xã Mường Lèo",
    "Xã Mường Và",
    "Xã Phù Yên",
    "Xã Quỳnh Nhai",
    "Xã Sông Mã",
    "Xã Thuận Châu",
    "Xã Vân Hồ",
    "Xã Yên Châu",
    "Thị trấn Bắc Yên",
    "Thị trấn Hát Lót",
    "Thị trấn Ít Ong",
    "Thị trấn Mộc Châu",
    "Thị trấn Mường La",
    "Thị trấn NT Mộc Châu",
    "Thị trấn Phù Yên",
    "Thị trấn Quỳnh Nhai",
    "Thị trấn Sông Mã",
    "Thị trấn Thuận Châu",
    "Thị trấn Yên Châu",
  ],

  // ══════════════════════════════════════════
  // LÀO CAI  (= Lào Cai + Yên Bái)
  // ══════════════════════════════════════════
  "Lào Cai": [
    "Phường Bắc Cường",
    "Phường Bắc Lệnh",
    "Phường Bình Minh",
    "Phường Cốc Lếu",
    "Phường Duyên Hải",
    "Phường Kim Tân",
    "Phường Lào Cai",
    "Phường Nam Cường",
    "Phường Phố Mới",
    "Phường Pom Hán",
    "Phường Thống Nhất",
    "Phường Xuân Tăng",
    // Từ Yên Bái
    "Phường Đồng Tâm",
    "Phường Hồng Hà",
    "Phường Minh Tân",
    "Phường Nguyễn Thái Học",
    "Phường Nguyễn Phúc",
    "Phường Yên Ninh",
    "Phường Yên Thịnh",
    // Xã
    "Xã Bảo Hà",
    "Xã Bảo Thắng",
    "Xã Bảo Yên",
    "Xã Bắc Hà",
    "Xã Bát Xát",
    "Xã Mường Khương",
    "Xã Sa Pa",
    "Xã Si Ma Cai",
    "Xã Văn Bàn",
    "Xã Lục Yên",
    "Xã Mù Cang Chải",
    "Xã Nghĩa Lộ",
    "Xã Trạm Tấu",
    "Xã Trấn Yên",
    "Xã Văn Chấn",
    "Xã Văn Yên",
    "Xã Yên Bình",
    "Thị trấn Bắc Hà",
    "Thị trấn Khánh Yên",
    "Thị trấn Mường Khương",
    "Thị trấn Sa Pa",
    "Thị trấn Si Ma Cai",
    "Thị trấn Thác Bà",
    "Thị trấn Yên Bình",
  ],

  // ══════════════════════════════════════════
  // TUYÊN QUANG  (= Tuyên Quang + Hà Giang)
  // ══════════════════════════════════════════
  "Tuyên Quang": [
    "Phường An Tường",
    "Phường Đội Cấn",
    "Phường Hưng Thành",
    "Phường Minh Xuân",
    "Phường Mỹ Lâm",
    "Phường Nông Tiến",
    "Phường Phan Thiết",
    "Phường Tân Hà",
    "Phường Tân Quang",
    // Từ Hà Giang
    "Phường Minh Khai",
    "Phường Ngọc Hà",
    "Phường Nguyễn Trãi",
    "Phường Quang Trung",
    "Phường Trần Phú",
    // Xã
    "Xã Bắc Quang",
    "Xã Chiêm Hóa",
    "Xã Đồng Yên",
    "Xã Hàm Yên",
    "Xã Hoàng Su Phì",
    "Xã Lâm Bình",
    "Xã Na Hang",
    "Xã Quản Bạ",
    "Xã Sơn Dương",
    "Xã Vị Xuyên",
    "Xã Xín Mần",
    "Xã Yên Sơn",
    "Thị trấn Vĩnh Lộc",
    "Thị trấn Tân Yên",
    "Thị trấn Nà Phặc",
    "Thị trấn Vị Xuyên",
  ],

  // ══════════════════════════════════════════
  // THÁI NGUYÊN  (= Thái Nguyên + Bắc Kạn)
  // ══════════════════════════════════════════
  "Thái Nguyên": [
    "Phường Cam Giá",
    "Phường Chùa Hang",
    "Phường Gia Sàng",
    "Phường Hoàng Văn Thụ",
    "Phường Hương Sơn",
    "Phường Phan Đình Phùng",
    "Phường Phú Xá",
    "Phường Quang Trung",
    "Phường Tân Long",
    "Phường Tân Thành",
    "Phường Tân Thịnh",
    "Phường Trung Thành",
    "Phường Túc Duyên",
    // Từ Bắc Kạn
    "Phường Đức Xuân",
    "Phường Huyền Tụng",
    "Phường Nguyễn Thị Minh Khai",
    "Phường Phùng Chí Kiên",
    "Phường Sông Cầu",
    // Xã
    "Xã Bắc Kạn",
    "Xã Ba Bể",
    "Xã Bắc Mê",
    "Xã Chợ Đồn",
    "Xã Chợ Mới",
    "Xã Định Hóa",
    "Xã Đại Từ",
    "Xã Đồng Hỷ",
    "Xã Na Rì",
    "Xã Ngân Sơn",
    "Xã Phú Bình",
    "Xã Phú Lương",
    "Xã Phổ Yên",
    "Xã Sông Công",
    "Xã Võ Nhai",
    "Xã Yên Thế",
    "Thị trấn Ba Bể",
    "Thị trấn Bằng Lũng",
    "Thị trấn Chợ Mới",
    "Thị trấn Chợ Rã",
    "Thị trấn Đình Cả",
    "Thị trấn Hùng Sơn",
    "Thị trấn Đu",
    "Thị trấn Nà Phặc",
    "Thị trấn Phú Thông",
    "Thị trấn Sông Cầu",
    "Thị trấn Trại Cau",
  ],

  // ══════════════════════════════════════════
  // LẠNG SƠN  (không sáp nhập tỉnh)
  // ══════════════════════════════════════════
  "Lạng Sơn": [
    "Phường Chi Lăng",
    "Phường Đông Kinh",
    "Phường Hoàng Văn Thụ",
    "Phường Tam Thanh",
    "Phường Tân Thành",
    "Phường Vĩnh Trại",
    "Phường Vũ Minh",
    "Xã Bắc Sơn",
    "Xã Bình Gia",
    "Xã Cao Lộc",
    "Xã Chi Lăng",
    "Xã Đình Lập",
    "Xã Hữu Lũng",
    "Xã Lộc Bình",
    "Xã Tràng Định",
    "Xã Văn Lãng",
    "Xã Văn Quan",
    "Thị trấn Bắc Sơn",
    "Thị trấn Bình Gia",
    "Thị trấn Cao Lộc",
    "Thị trấn Chi Lăng",
    "Thị trấn Đình Lập",
    "Thị trấn Đồng Mỏ",
    "Thị trấn Hữu Lũng",
    "Thị trấn Lộc Bình",
    "Thị trấn Na Dương",
    "Thị trấn Na Sầm",
    "Thị trấn Tràng Định",
    "Thị trấn Văn Quan",
  ],

  // ══════════════════════════════════════════
  // QUẢNG NINH  (không sáp nhập tỉnh)
  // ══════════════════════════════════════════
  "Quảng Ninh": [
    "Phường Bãi Cháy",
    "Phường Bạch Đằng",
    "Phường Giếng Đáy",
    "Phường Hà Khánh",
    "Phường Hà Lầm",
    "Phường Hà Phong",
    "Phường Hà Trung",
    "Phường Hà Tu",
    "Phường Hồng Gai",
    "Phường Hùng Thắng",
    "Phường Tuần Châu",
    "Phường Việt Hưng",
    "Phường Yết Kiêu",
    "Phường Cẩm Bình",
    "Phường Cẩm Đông",
    "Phường Cẩm Nam",
    "Phường Cẩm Phú",
    "Phường Cẩm Sơn",
    "Phường Cẩm Tây",
    "Phường Cẩm Thạch",
    "Phường Cẩm Thành",
    "Phường Cẩm Thủy",
    "Phường Cẩm Thượng",
    "Phường Cẩm Trung",
    "Phường Mông Dương",
    "Phường Quang Hanh",
    "Phường Cộng Hòa",
    "Phường Hà Tu",
    "Phường Hòa Lạc",
    "Phường Thái Bình",
    "Phường Uông Bí",
    "Phường Vàng Danh",
    "Phường Yên Thanh",
    "Phường Đông Mai",
    "Phường Điền Công",
    "Phường Quảng Yên",
    "Phường Tân An",
    "Phường Đông Triều",
    "Phường Mạo Khê",
    "Phường Tràng An",
    "Phường Bình Khê",
    "Phường Yên Thọ",
    "Xã Ba Chẽ",
    "Xã Bình Liêu",
    "Xã Cô Tô",
    "Xã Đầm Hà",
    "Xã Hải Hà",
    "Xã Hoành Bồ",
    "Xã Móng Cái",
    "Xã Tiên Yên",
    "Xã Vân Đồn",
    "Thị trấn Ba Chẽ",
    "Thị trấn Bình Liêu",
    "Thị trấn Cô Tô",
    "Thị trấn Đầm Hà",
    "Thị trấn Hải Hà",
    "Thị trấn Tiên Yên",
  ],

  // ══════════════════════════════════════════
  // BẮC NINH  (= Bắc Ninh + Bắc Giang)
  // ══════════════════════════════════════════
  "Bắc Ninh": [
    "Phường Đáp Cầu",
    "Phường Kinh Bắc",
    "Phường Ninh Xá",
    "Phường Suối Hoa",
    "Phường Thị Cầu",
    "Phường Tiền An",
    "Phường Vệ An",
    "Phường Vũ Ninh",
    "Phường Đình Bảng",
    "Phường Từ Sơn",
    "Phường Tân Hồng",
    // Từ Bắc Giang
    "Phường Dĩnh Kế",
    "Phường Hoàng Văn Thụ",
    "Phường Lê Lợi",
    "Phường Mỹ Độ",
    "Phường Ngô Quyền",
    "Phường Song Mai",
    "Phường Thọ Xương",
    "Phường Trần Nguyên Hãn",
    "Phường Trần Phú",
    "Phường Xương Giang",
    // Xã
    "Xã Gia Bình",
    "Xã Hiệp Hòa",
    "Xã Lạng Giang",
    "Xã Lục Nam",
    "Xã Lục Ngạn",
    "Xã Lương Tài",
    "Xã Quế Võ",
    "Xã Sơn Động",
    "Xã Tân Yên",
    "Xã Thuận Thành",
    "Xã Tiên Du",
    "Xã Việt Yên",
    "Xã Yên Dũng",
    "Xã Yên Thế",
    "Thị trấn Chờ",
    "Thị trấn Gia Bình",
    "Thị trấn Hồ",
    "Thị trấn Lim",
    "Thị trấn Phố Mới",
    "Thị trấn Thứa",
    "Thị trấn An Châu",
    "Thị trấn Bố Hạ",
    "Thị trấn Cao Thượng",
    "Thị trấn Đồi Ngô",
    "Thị trấn Nham Biền",
  ],

  // ══════════════════════════════════════════
  // HƯNG YÊN  (= Hưng Yên + Thái Bình)
  // ══════════════════════════════════════════
  "Hưng Yên": [
    "Phường An Tảo",
    "Phường Hiến Nam",
    "Phường Hồng Châu",
    "Phường Lam Sơn",
    "Phường Lê Lợi",
    "Phường Minh Khai",
    "Phường Nguyễn Du",
    "Phường Nhân Hòa",
    "Phường Quang Trung",
    // Từ Thái Bình
    "Phường Bồ Xuyên",
    "Phường Đề Thám",
    "Phường Hoàng Diệu",
    "Phường Kỳ Bá",
    "Phường Phú Khánh",
    "Phường Quang Trung",
    "Phường Tiền Phong",
    "Phường Trần Hưng Đạo",
    "Phường Trần Lãm",
    // Xã
    "Xã Ân Thi",
    "Xã Kim Động",
    "Xã Khoái Châu",
    "Xã Mỹ Hào",
    "Xã Phù Cừ",
    "Xã Tiên Lữ",
    "Xã Văn Giang",
    "Xã Văn Lâm",
    "Xã Yên Mỹ",
    "Xã Đông Hưng",
    "Xã Hưng Hà",
    "Xã Kiến Xương",
    "Xã Quỳnh Phụ",
    "Xã Thái Thụy",
    "Xã Tiền Hải",
    "Xã Vũ Thư",
    "Thị trấn Ân Thi",
    "Thị trấn Khoái Châu",
    "Thị trấn Lương Bằng",
    "Thị trấn Vương",
    "Thị trấn Đông Hưng",
    "Thị trấn Hưng Hà",
    "Thị trấn Tiền Hải",
  ],

  // ══════════════════════════════════════════
  // PHÚ THỌ  (= Phú Thọ + Vĩnh Phúc + Hòa Bình)
  // ══════════════════════════════════════════
  "Phú Thọ": [
    "Phường Bến Gót",
    "Phường Dữu Lâu",
    "Phường Gia Cẩm",
    "Phường Minh Nông",
    "Phường Minh Phương",
    "Phường Nông Trang",
    "Phường Phong Châu",
    "Phường Thanh Miếu",
    "Phường Tân Dân",
    "Phường Tiên Cát",
    "Phường Vân Cơ",
    "Phường Vân Phú",
    // Từ Vĩnh Phúc
    "Phường Đống Đa",
    "Phường Hội Hợp",
    "Phường Khai Quang",
    "Phường Liên Bảo",
    "Phường Ngô Quyền",
    "Phường Tích Sơn",
    "Phường Trưng Dương",
    "Phường Trưng Trắc",
    // Từ Hòa Bình
    "Phường Chăm Mát",
    "Phường Dân Chủ",
    "Phường Đồng Tiến",
    "Phường Hữu Nghị",
    "Phường Phương Lâm",
    "Phường Tân Hòa",
    "Phường Tân Thịnh",
    "Phường Thái Bình",
    "Phường Thịnh Lang",
    // Xã
    "Xã Cẩm Khê",
    "Xã Đoan Hùng",
    "Xã Hạ Hòa",
    "Xã Lâm Thao",
    "Xã Phù Ninh",
    "Xã Tam Nông",
    "Xã Tân Sơn",
    "Xã Thanh Ba",
    "Xã Thanh Sơn",
    "Xã Thanh Thủy",
    "Xã Yên Lập",
    "Xã Bình Xuyên",
    "Xã Lập Thạch",
    "Xã Sông Lô",
    "Xã Tam Đảo",
    "Xã Tam Dương",
    "Xã Vĩnh Tường",
    "Xã Yên Lạc",
    "Xã Cao Phong",
    "Xã Đà Bắc",
    "Xã Kim Bôi",
    "Xã Kỳ Sơn",
    "Xã Lạc Sơn",
    "Xã Lạc Thủy",
    "Xã Lương Sơn",
    "Xã Mai Châu",
    "Xã Tân Lạc",
    "Xã Yên Thủy",
    "Thị trấn Hưng Hóa",
    "Thị trấn Lâm Thao",
    "Thị trấn Phong Châu",
  ],

  // ══════════════════════════════════════════
  // NINH BÌNH  (= Ninh Bình + Hà Nam + Nam Định)
  // ══════════════════════════════════════════
  "Ninh Bình": [
    "Phường Bích Đào",
    "Phường Đông Thành",
    "Phường Nam Bình",
    "Phường Nam Thành",
    "Phường Ninh Khánh",
    "Phường Ninh Phong",
    "Phường Ninh Sơn",
    "Phường Phúc Thành",
    "Phường Tân Thành",
    "Phường Thanh Bình",
    // Từ Hà Nam
    "Phường Châu Sơn",
    "Phường Hai Bà Trưng",
    "Phường Lam Hạ",
    "Phường Liêm Chính",
    "Phường Lương Khánh Thiện",
    "Phường Minh Khai",
    "Phường Quang Trung",
    "Phường Thanh Tuyền",
    "Phường Trần Hưng Đạo",
    // Từ Nam Định
    "Phường Bà Triệu",
    "Phường Cửa Bắc",
    "Phường Cửa Nam",
    "Phường Hạ Long",
    "Phường Lộc Hòa",
    "Phường Lộc Vượng",
    "Phường Năng Tĩnh",
    "Phường Ngô Quyền",
    "Phường Nguyễn Du",
    "Phường Phan Đình Phùng",
    "Phường Quang Trung",
    "Phường Thống Nhất",
    "Phường Trần Đăng Ninh",
    "Phường Trần Quang Khải",
    "Phường Trường Thi",
    "Phường Văn Miếu",
    // Xã
    "Xã Gia Viễn",
    "Xã Hoa Lư",
    "Xã Kim Sơn",
    "Xã Nho Quan",
    "Xã Tam Điệp",
    "Xã Yên Khánh",
    "Xã Yên Mô",
    "Xã Bình Lục",
    "Xã Duy Tiên",
    "Xã Kim Bảng",
    "Xã Lý Nhân",
    "Xã Thanh Liêm",
    "Xã Giao Thủy",
    "Xã Hải Hậu",
    "Xã Mỹ Lộc",
    "Xã Nam Trực",
    "Xã Nghĩa Hưng",
    "Xã Trực Ninh",
    "Xã Vụ Bản",
    "Xã Xuân Trường",
    "Xã Ý Yên",
    "Thị trấn Me",
    "Thị trấn Thiên Tôn",
  ],

  // ══════════════════════════════════════════
  // THANH HÓA  (không sáp nhập tỉnh)
  // ══════════════════════════════════════════
  "Thanh Hóa": [
    "Phường An Hoạch",
    "Phường Ba Đình",
    "Phường Điện Biên",
    "Phường Đông Cương",
    "Phường Đông Hương",
    "Phường Đông Sơn",
    "Phường Đông Thọ",
    "Phường Đông Vệ",
    "Phường Hàm Rồng",
    "Phường Lam Sơn",
    "Phường Nam Ngạn",
    "Phường Ngọc Trạo",
    "Phường Phú Sơn",
    "Phường Quảng Hưng",
    "Phường Quảng Thắng",
    "Phường Quảng Thành",
    "Phường Tào Xuyên",
    "Phường Trường Thi",
    // Xã
    "Xã Bá Thước",
    "Xã Cẩm Thủy",
    "Xã Hà Trung",
    "Xã Hậu Lộc",
    "Xã Hoằng Hóa",
    "Xã Lang Chánh",
    "Xã Mường Lát",
    "Xã Nga Sơn",
    "Xã Ngọc Lặc",
    "Xã Như Xuân",
    "Xã Như Thanh",
    "Xã Nông Cống",
    "Xã Quan Hóa",
    "Xã Quan Sơn",
    "Xã Quảng Xương",
    "Xã Sầm Sơn",
    "Xã Thiệu Hóa",
    "Xã Thọ Xuân",
    "Xã Thường Xuân",
    "Xã Tĩnh Gia",
    "Xã Triệu Sơn",
    "Xã Vĩnh Lộc",
    "Xã Yên Định",
    "Thị trấn Bút Sơn",
    "Thị trấn Cành Nàng",
    "Thị trấn Hà Trung",
    "Thị trấn Hậu Lộc",
    "Thị trấn Nga Sơn",
    "Thị trấn Ngọc Lặc",
    "Thị trấn Nưa",
    "Thị trấn Sầm Sơn",
    "Thị trấn Tĩnh Gia",
    "Thị trấn Thọ Xuân",
  ],

  // ══════════════════════════════════════════
  // NGHỆ AN  (không sáp nhập tỉnh)
  // ══════════════════════════════════════════
  "Nghệ An": [
    "Phường Bến Thủy",
    "Phường Cửa Nam",
    "Phường Đội Cung",
    "Phường Hà Huy Tập",
    "Phường Hồng Sơn",
    "Phường Hưng Bình",
    "Phường Hưng Dũng",
    "Phường Hưng Phúc",
    "Phường Lê Lợi",
    "Phường Lê Mao",
    "Phường Quang Phong",
    "Phường Quang Tiến",
    "Phường Trung Đô",
    "Phường Trường Thi",
    "Phường Vinh Tân",
    // Xã
    "Xã Anh Sơn",
    "Xã Con Cuông",
    "Xã Diễn Châu",
    "Xã Đô Lương",
    "Xã Hưng Nguyên",
    "Xã Kỳ Sơn",
    "Xã Nam Đàn",
    "Xã Nghĩa Đàn",
    "Xã Nghi Lộc",
    "Xã Nghi Xuân",
    "Xã Quế Phong",
    "Xã Quỳ Châu",
    "Xã Quỳ Hợp",
    "Xã Quỳnh Lưu",
    "Xã Tân Kỳ",
    "Xã Thanh Chương",
    "Xã Tương Dương",
    "Xã Yên Thành",
    "Thị xã Cửa Lò",
    "Thị xã Hoàng Mai",
    "Thị xã Thái Hòa",
  ],

  // ══════════════════════════════════════════
  // HÀ TĨNH  (không sáp nhập tỉnh)
  // ══════════════════════════════════════════
  "Hà Tĩnh": [
    "Phường Bắc Hà",
    "Phường Hà Huy Tập",
    "Phường Nam Hà",
    "Phường Nguyễn Du",
    "Phường Tân Giang",
    "Phường Thạch Linh",
    "Phường Thạch Quý",
    "Phường Trần Phú",
    "Phường Văn Yên",
    // Xã
    "Xã Cẩm Xuyên",
    "Xã Can Lộc",
    "Xã Đức Thọ",
    "Xã Hương Khê",
    "Xã Hương Sơn",
    "Xã Kỳ Anh",
    "Xã Lộc Hà",
    "Xã Nghi Xuân",
    "Xã Thạch Hà",
    "Xã Vũ Quang",
    "Thị xã Hồng Lĩnh",
    "Thị xã Kỳ Anh",
  ],

  // ══════════════════════════════════════════
  // QUẢNG TRỊ  (= Quảng Trị + Quảng Bình)
  // ══════════════════════════════════════════
  "Quảng Trị": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường Đông Lương",
    "Phường Đông Thanh",
    "Phường Đông Thanh",
    // Từ Quảng Bình
    "Phường Bắc Lý",
    "Phường Đồng Hới",
    "Phường Đồng Mỹ",
    "Phường Đồng Phú",
    "Phường Đồng Sơn",
    "Phường Hải Đình",
    "Phường Hải Thành",
    "Phường Nam Lý",
    "Phường Phú Hải",
    "Phường Phú Thủy",
    // Xã
    "Xã Bố Trạch",
    "Xã Cam Lộ",
    "Xã Cồn Cỏ",
    "Xã Đakrông",
    "Xã Đồng Hới",
    "Xã Gio Linh",
    "Xã Hải Lăng",
    "Xã Hướng Hóa",
    "Xã Lệ Thủy",
    "Xã Minh Hóa",
    "Xã Quảng Ninh",
    "Xã Quảng Trạch",
    "Xã Triệu Phong",
    "Xã Tuyên Hóa",
    "Xã Vĩnh Linh",
    "Thị trấn Bến Quan",
    "Thị trấn Cửa Tùng",
    "Thị trấn Hồ Xá",
    "Thị trấn Gio Linh",
    "Thị trấn Diên Sanh",
    "Thị trấn Lao Bảo",
  ],

  // ══════════════════════════════════════════
  // QUẢNG NGÃI  (= Quảng Ngãi + Kon Tum)
  // ══════════════════════════════════════════
  "Quảng Ngãi": [
    "Phường Chánh Lộ",
    "Phường Lê Hồng Phong",
    "Phường Nghĩa Chánh",
    "Phường Nghĩa Lộ",
    "Phường Nguyễn Nghiêm",
    "Phường Quảng Phú",
    "Phường Trần Hưng Đạo",
    "Phường Trần Phú",
    // Từ Kon Tum
    "Phường Duy Tân",
    "Phường Lê Lợi",
    "Phường Ngô Mây",
    "Phường Nguyễn Trãi",
    "Phường Quang Trung",
    "Phường Thắng Lợi",
    "Phường Thống Nhất",
    "Phường Trần Hưng Đạo",
    "Phường Trường Chinh",
    "Phường Vinh Quang",
    // Xã
    "Xã Ba Tơ",
    "Xã Bình Sơn",
    "Xã Đắk Glei",
    "Xã Đắk Hà",
    "Xã Đắk Tô",
    "Xã Kon Plông",
    "Xã Kon Rẫy",
    "Xã Lý Sơn",
    "Xã Minh Long",
    "Xã Mộ Đức",
    "Xã Nghĩa Hành",
    "Xã Ngọc Hồi",
    "Xã Sa Thầy",
    "Xã Sơn Hà",
    "Xã Sơn Tây",
    "Xã Sơn Tịnh",
    "Xã Tu Mơ Rông",
    "Xã Tư Nghĩa",
    "Xã Tây Trà",
    "Xã Trà Bồng",
    "Xã Trà My",
    "Xã Trà Bổng",
    "Thị trấn Ba Tơ",
    "Thị trấn Chợ Chùa",
    "Thị trấn Đắk Tô",
    "Thị trấn Đức Phổ",
    "Thị trấn Mộ Đức",
    "Thị trấn Sa Thầy",
    "Thị trấn Trà Xuân",
  ],

  // ══════════════════════════════════════════
  // GIA LAI  (= Gia Lai + Bình Định)
  // ══════════════════════════════════════════
  "Gia Lai": [
    "Phường Chi Lăng",
    "Phường Diên Hồng",
    "Phường Đống Đa",
    "Phường Hoa Lư",
    "Phường Hội Phú",
    "Phường Hội Thương",
    "Phường Ia Kring",
    "Phường Phù Đổng",
    "Phường Tây Sơn",
    "Phường Thắng Lợi",
    "Phường Thống Nhất",
    "Phường Trà Bá",
    "Phường Yên Đỗ",
    "Phường Yên Thế",
    // Từ Bình Định
    "Phường Bình Định",
    "Phường Đống Đa",
    "Phường Ghềnh Ráng",
    "Phường Hải Cảng",
    "Phường Lê Hồng Phong",
    "Phường Lý Thường Kiệt",
    "Phường Ngô Mây",
    "Phường Nhơn Bình",
    "Phường Nhơn Phú",
    "Phường Thị Nại",
    "Phường Trần Hưng Đạo",
    "Phường Trần Phú",
    // Xã
    "Xã An Khê",
    "Xã Ayun Pa",
    "Xã Chư Păh",
    "Xã Chư Prông",
    "Xã Chư Pưh",
    "Xã Chư Sê",
    "Xã Đắk Đoa",
    "Xã Đắk Pơ",
    "Xã Đức Cơ",
    "Xã Ia Grai",
    "Xã Ia Pa",
    "Xã KBang",
    "Xã Kông Chro",
    "Xã Krông Pa",
    "Xã Mang Yang",
    "Xã Phú Thiện",
    "Xã An Lão",
    "Xã Hoài Ân",
    "Xã Hoài Nhơn",
    "Xã Phù Cát",
    "Xã Phù Mỹ",
    "Xã Tây Sơn",
    "Xã Tuy Phước",
    "Xã Vân Canh",
    "Xã Vĩnh Thạnh",
    "Xã An Nhơn",
  ],

  // ══════════════════════════════════════════
  // ĐẮK LẮK  (= Đắk Lắk + Phú Yên)
  // ══════════════════════════════════════════
  "Đắk Lắk": [
    "Phường An Lạc",
    "Phường Ea Tam",
    "Phường Hiệp Thành",
    "Phường Khánh Xuân",
    "Phường Tân An",
    "Phường Tân Hòa",
    "Phường Tân Lập",
    "Phường Tân Lợi",
    "Phường Tân Thành",
    "Phường Thắng Lợi",
    "Phường Thành Nhất",
    "Phường Thống Nhất",
    "Phường Tự An",
    // Từ Phú Yên
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường An Phú",
    "Phường Phú Đông",
    "Phường Phú Lâm",
    "Phường Phú Thạnh",
    // Xã
    "Xã Buôn Đôn",
    "Xã Cư Jút",
    "Xã Cư M'gar",
    "Xã Ea H'leo",
    "Xã Ea Kar",
    "Xã Ea Súp",
    "Xã Krông Ana",
    "Xã Krông Bông",
    "Xã Krông Búk",
    "Xã Krông Năng",
    "Xã Krông Pắc",
    "Xã Lắk",
    "Xã M'Đrắk",
    "Xã Đông Hòa",
    "Xã Đồng Xuân",
    "Xã Phú Hòa",
    "Xã Sông Cầu",
    "Xã Sông Hinh",
    "Xã Sơn Hòa",
    "Xã Tây Hòa",
    "Xã Tuy An",
    "Xã Tuy Hòa",
    "Xã Krông Pa",
  ],

  // ══════════════════════════════════════════
  // KHÁNH HÒA  (= Khánh Hòa + Ninh Thuận)
  // ══════════════════════════════════════════
  "Khánh Hòa": [
    "Phường Lộc Thọ",
    "Phường Ngọc Hiệp",
    "Phường Phước Hải",
    "Phường Phước Hòa",
    "Phường Phước Long",
    "Phường Phước Tân",
    "Phường Tân Lập",
    "Phường Vạn Thạnh",
    "Phường Vĩnh Hải",
    "Phường Vĩnh Hòa",
    "Phường Vĩnh Nguyên",
    "Phường Vĩnh Phước",
    "Phường Vĩnh Thọ",
    "Phường Vĩnh Trường",
    "Phường Xương Huân",
    // Từ Ninh Thuận
    "Phường Đài Sơn",
    "Phường Đô Vinh",
    "Phường Kinh Dinh",
    "Phường Mỹ Bình",
    "Phường Mỹ Đông",
    "Phường Mỹ Hải",
    "Phường Mỹ Hương",
    "Phường Mỹ Thanh",
    "Phường Phủ Hà",
    "Phường Phước Mỹ",
    "Phường Tấn Tài",
    // Xã
    "Xã Cam Lâm",
    "Xã Cam Ranh",
    "Xã Diên Khánh",
    "Xã Khánh Sơn",
    "Xã Khánh Vĩnh",
    "Xã Ninh Hòa",
    "Xã Vạn Ninh",
    "Xã Bác Ái",
    "Xã Ninh Hải",
    "Xã Ninh Phước",
    "Xã Ninh Sơn",
    "Xã Thuận Bắc",
    "Xã Thuận Nam",
    "Thị trấn Cam Đức",
    "Thị trấn Diên Khánh",
    "Thị trấn Khánh Vĩnh",
    "Thị trấn Ninh Hòa",
    "Thị trấn Tân Bình",
    "Thị trấn Vạn Giã",
  ],

  // ══════════════════════════════════════════
  // LÂM ĐỒNG  (= Lâm Đồng + Đắk Nông + Bình Thuận)
  // ══════════════════════════════════════════
  "Lâm Đồng": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    "Phường 11",
    "Phường 12",
    // Từ Đắk Nông
    "Phường Nghĩa Đức",
    "Phường Nghĩa Phú",
    "Phường Nghĩa Tân",
    "Phường Nghĩa Thành",
    "Phường Nghĩa Trung",
    // Từ Bình Thuận
    "Phường Bình Hưng",
    "Phường Đức Long",
    "Phường Đức Nghĩa",
    "Phường Đức Thắng",
    "Phường Hàm Tiến",
    "Phường Lạc Đạo",
    "Phường Mũi Né",
    "Phường Phú Hài",
    "Phường Phú Tài",
    "Phường Phú Thủy",
    "Phường Phú Trinh",
    "Phường Thanh Hải",
    "Phường Xuân An",
    // Xã
    "Xã Bảo Lâm",
    "Xã Bảo Lộc",
    "Xã Cát Tiên",
    "Xã Di Linh",
    "Xã Đam Rông",
    "Xã Đơn Dương",
    "Xã Đức Trọng",
    "Xã Lạc Dương",
    "Xã Lâm Hà",
    "Xã Cư Jút",
    "Xã Đắk G'long",
    "Xã Đắk Mil",
    "Xã Đắk R'lấp",
    "Xã Đắk Song",
    "Xã Krông Nô",
    "Xã Tuy Đức",
    "Xã Bắc Bình",
    "Xã Đức Linh",
    "Xã Hàm Tân",
    "Xã Hàm Thuận Bắc",
    "Xã Hàm Thuận Nam",
    "Xã Phú Quý",
    "Xã Tánh Linh",
    "Xã Tuy Phong",
    "Thị xã La Gi",
  ],

  // ══════════════════════════════════════════
  // ĐỒNG NAI  (= Đồng Nai + Bình Phước)
  // ══════════════════════════════════════════
  "Đồng Nai": [
    "Phường An Bình",
    "Phường Bình Đa",
    "Phường Hòa Bình",
    "Phường Long Bình",
    "Phường Long Bình Tân",
    "Phường Quang Vinh",
    "Phường Quyết Thắng",
    "Phường Tam Hiệp",
    "Phường Tam Hòa",
    "Phường Tân Hiệp",
    "Phường Tân Mai",
    "Phường Tân Phong",
    "Phường Tân Tiến",
    "Phường Tân Vạn",
    "Phường Thanh Bình",
    "Phường Thống Nhất",
    "Phường Trảng Dài",
    "Phường Trung Dũng",
    // Từ Bình Phước
    "Phường An Lộc",
    "Phường Hưng Chiến",
    "Phường Phú Đức",
    "Phường Phú Lợi",
    "Phường Phú Thịnh",
    "Phường Sơn Giang",
    "Phường Tiến Thành",
    // Xã
    "Xã Biên Hòa",
    "Xã Cẩm Mỹ",
    "Xã Định Quán",
    "Xã Long Khánh",
    "Xã Long Thành",
    "Xã Nhơn Trạch",
    "Xã Tân Phú",
    "Xã Thống Nhất",
    "Xã Trảng Bom",
    "Xã Vĩnh Cửu",
    "Xã Xuân Lộc",
    "Xã Bù Đăng",
    "Xã Bù Đốp",
    "Xã Bù Gia Mập",
    "Xã Chơn Thành",
    "Xã Đồng Phú",
    "Xã Đồng Xoài",
    "Xã Hớn Quản",
    "Xã Lộc Ninh",
    "Xã Phước Long",
  ],

  // ══════════════════════════════════════════
  // TÂY NINH  (= Tây Ninh + Long An)
  // ══════════════════════════════════════════
  "Tây Ninh": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường Hiệp Ninh",
    "Phường Ninh Sơn",
    "Phường Ninh Thạnh",
    // Từ Long An
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường Khánh Hậu",
    "Phường Tân Khánh",
    // Xã
    "Xã Bến Cầu",
    "Xã Châu Thành",
    "Xã Dương Minh Châu",
    "Xã Gò Dầu",
    "Xã Hòa Thành",
    "Xã Tân Biên",
    "Xã Tân Châu",
    "Xã Trảng Bàng",
    "Xã Bến Lức",
    "Xã Cần Đước",
    "Xã Cần Giuộc",
    "Xã Châu Thành",
    "Xã Đức Hòa",
    "Xã Đức Huệ",
    "Xã Mộc Hóa",
    "Xã Tân An",
    "Xã Tân Hưng",
    "Xã Tân Thạnh",
    "Xã Tân Trụ",
    "Xã Thạnh Hóa",
    "Xã Thủ Thừa",
    "Xã Vĩnh Hưng",
  ],

  // ══════════════════════════════════════════
  // AN GIANG  (= An Giang + Kiên Giang)
  // ══════════════════════════════════════════
  "An Giang": [
    "Phường Bình Đức",
    "Phường Bình Khánh",
    "Phường Đông Xuyên",
    "Phường Mỹ Bình",
    "Phường Mỹ Long",
    "Phường Mỹ Phước",
    "Phường Mỹ Quý",
    "Phường Mỹ Thạnh",
    "Phường Mỹ Xuyên",
    "Phường Núi Sam",
    // Từ Kiên Giang
    "Phường An Bình",
    "Phường Dương Đông",
    "Phường Đông Hồ",
    "Phường Phan Thị Ràng",
    "Phường Rạch Sỏi",
    "Phường Thủy Biều",
    "Phường Vĩnh Bảo",
    "Phường Vĩnh Hiệp",
    "Phường Vĩnh Lạc",
    "Phường Vĩnh Lợi",
    "Phường Vĩnh Quang",
    "Phường Vĩnh Thanh",
    "Phường Vĩnh Thanh Vân",
    "Phường Vĩnh Thông",
    // Xã
    "Xã An Phú",
    "Xã Châu Đốc",
    "Xã Châu Phú",
    "Xã Châu Thành",
    "Xã Chợ Mới",
    "Xã Phú Tân",
    "Xã Tân Châu",
    "Xã Thoại Sơn",
    "Xã Tịnh Biên",
    "Xã Tri Tôn",
    "Xã An Biên",
    "Xã An Minh",
    "Xã Châu Thành",
    "Xã Giang Thành",
    "Xã Giồng Riềng",
    "Xã Gò Quao",
    "Xã Hà Tiên",
    "Xã Hòn Đất",
    "Xã Kiên Hải",
    "Xã Kiên Lương",
    "Xã Phú Quốc",
    "Xã Vĩnh Thuận",
    "Xã U Minh Thượng",
  ],

  // ══════════════════════════════════════════
  // ĐỒNG THÁP  (= Đồng Tháp + Tiền Giang)
  // ══════════════════════════════════════════
  "Đồng Tháp": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 6",
    "Phường 11",
    "Phường Hòa Thuận",
    "Phường Mỹ Phú",
    "Phường Tân Quy Đông",
    // Từ Tiền Giang
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    // Xã
    "Xã Cao Lãnh",
    "Xã Châu Thành",
    "Xã Hồng Ngự",
    "Xã Lai Vung",
    "Xã Lấp Vò",
    "Xã Sa Đéc",
    "Xã Tam Nông",
    "Xã Tân Hồng",
    "Xã Tháp Mười",
    "Xã Thanh Bình",
    "Xã Cai Lậy",
    "Xã Cái Bè",
    "Xã Châu Thành",
    "Xã Chợ Gạo",
    "Xã Gò Công",
    "Xã Gò Công Đông",
    "Xã Gò Công Tây",
    "Xã Tân Phú Đông",
    "Xã Tân Phước",
    "Xã Tân Phú Đông",
  ],

  // ══════════════════════════════════════════
  // VĨNH LONG  (= Vĩnh Long + Bến Tre + Trà Vinh)
  // ══════════════════════════════════════════
  "Vĩnh Long": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 8",
    "Phường 9",
    // Từ Bến Tre
    "Phường An Hội",
    "Phường Phú Khương",
    "Phường Phú Tân",
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    // Từ Trà Vinh
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    // Xã
    "Xã Bình Minh",
    "Xã Bình Tân",
    "Xã Long Hồ",
    "Xã Mang Thít",
    "Xã Tam Bình",
    "Xã Trà Ôn",
    "Xã Vũng Liêm",
    "Xã Ba Tri",
    "Xã Bình Đại",
    "Xã Châu Thành",
    "Xã Chợ Lách",
    "Xã Giồng Trôm",
    "Xã Mỏ Cày Bắc",
    "Xã Mỏ Cày Nam",
    "Xã Thạnh Phú",
    "Xã Càng Long",
    "Xã Cầu Kè",
    "Xã Cầu Ngang",
    "Xã Châu Thành",
    "Xã Duyên Hải",
    "Xã Tiểu Cần",
    "Xã Trà Cú",
  ],

  // ══════════════════════════════════════════
  // CÀ MAU  (= Cà Mau + Bạc Liêu)
  // ══════════════════════════════════════════
  "Cà Mau": [
    "Phường 1",
    "Phường 2",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    // Từ Bạc Liêu
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 5",
    "Phường 7",
    "Phường 8",
    "Phường Nhà Mát",
    // Xã
    "Xã Cái Nước",
    "Xã Châu Thành",
    "Xã Đầm Dơi",
    "Xã Năm Căn",
    "Xã Ngọc Hiển",
    "Xã Phú Tân",
    "Xã Thới Bình",
    "Xã Trần Văn Thời",
    "Xã U Minh",
    "Xã Đông Hải",
    "Xã Giá Rai",
    "Xã Hòa Bình",
    "Xã Hồng Dân",
    "Xã Phước Long",
    "Xã Vĩnh Lợi",
    "Xã Vĩnh Châu",
    "Thị trấn Cái Đôi Vàm",
    "Thị trấn Năm Căn",
    "Thị trấn Rạch Gốc",
    "Thị trấn Sông Đốc",
    "Thị trấn Trần Văn Thời",
    "Thị trấn U Minh",
    "Thị trấn Giá Rai",
    "Thị trấn Hộ Phòng",
    "Thị trấn Phước Long",
  ],
};

// ─────────────────────────────────────────────
// TIỆN ÍCH / HELPERS
// ─────────────────────────────────────────────

/** Trả về danh sách phường/xã của một tỉnh, hoặc [] nếu chưa có dữ liệu */
export function getWards(province: string): string[] {
  return WARDS_BY_PROVINCE[province] ?? [];
}

/** Kiểm tra tỉnh có tồn tại không */
export function isValidProvince(province: string): boolean {
  return PROVINCES.includes(province);
}

/** Trả về tổng số tỉnh/thành */
export function getTotalProvinces(): number {
  return PROVINCES.length;
}

/** Trả về tổng số xã/phường đã có dữ liệu */
export function getTotalWards(): number {
  return Object.values(WARDS_BY_PROVINCE).reduce(
    (sum, wards) => sum + wards.length,
    0,
  );
}
